# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testline_Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testlines',
            options={'verbose_name_plural': 'Testlines'},
        ),
    ]
