# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testline_Details', '0002_auto_20161028_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlines',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
