# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testline_Details', '0003_testlines_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlines',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
