# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testline_Details', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
