# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testline_Details', '0006_auto_20161031_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlines',
            name='slug',
        ),
    ]
