# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testline_Details', '0007_remove_testlines_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlines',
            name='IMSI',
        ),
        migrations.RemoveField(
            model_name='testlines',
            name='UEs',
        ),
        migrations.AddField(
            model_name='testlines',
            name='L2_switch_ip',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testlines',
            name='Login_details',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testlines',
            name='Port',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testlines',
            name='Remote_ip',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
